<ul class="m-footer-bd b-clearfix">
	<li><a href="/financialholdings/hr/jobs.html">人才招募</a></li>
	<li><a href="/financialholdings/announcement/announcement.html">法定揭露事項</a></li>
	<li><a href="/financialholdings/location/location_tw.html">海內外服務據點</a></li>
	<li><a href="/financialholdings/privacy_policy/privacy.html">隱私權聲明</a></li>
	<li><a href="/financialholdings/consumer_protection/consumer_protection.html">消費者保護</a></li>
	<li><a href="/financialholdings/service/contact.html">服務中心</a></li>
	<li><a href="/financialholdings/epaper/list.html">富邦理財電子報</a></li>
</ul>
<small class="m-footer-ft">© 富邦金融控股股份有限公司<br />建議瀏覽器版本：IE8 (含)、Chrome 40 (含)、Safari 5 (含)、FireFox 30 (含) 以上版本</small>
