<div class="m-nav-path ng-nav-path" ng-style="{'top' : Common.Nav.Path.Top , 'height' : Common.Nav.Path.Height}">
	<ul>
		<li ng-style="{'height' : Common.Nav.Path.Height}">
			<a href="javascript:;" class="ng-path">
				金控成員
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
			<!--[if lt IE 10]><span></span><![endif]-->
			<div>
				<ul>
					<li><a href="https://www.fubon.com/life/home/index.htm?ctype=B&cid=menu&oid=life" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦人壽</a></li>
					<li><a href="https://www.fubon.com/bank/home/index.htm?ctype=B&cid=menu&oid=bank" target="_blank"><i class="m-icon m-icon-chevron-right"></i>台北富邦銀行</a></li>
					<li><a href="https://www.fubon.com/life_vn/" target="_blank"><i class="m-icon m-icon-chevron-right" target="_blank"></i>富邦人壽(越南)</a></li>
					<li><a href="http://www.fubonbank.com.hk/web/html/index_c.html" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦銀行(香港)</a></li>
					<li><a href="http://www.fubonchina.com/" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦華一銀行(大陸)</a></li>
					<li><a href="https://www.fubon.com/insurance/home/index.htm?ctype=B&cid=menu&oid=insurance" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦產險</a></li>
					<li><a href="https://www.fubon.com/INS_VN/?ctype=B&cid=menu&oid=ins" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦產險(越南)</a></li>
					<li><a href="http://www.fubon.com.cn/insurance/" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦財險(大陸)</a></li>
					<li><a href="https://www.fubon.com/securities/home/index.htm?ctype=B&cid=menu&oid=securities" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦證券</a></li>
					<li><a href="https://www.fubon.com/asset-management/home/index.htm?ctype=B&cid=menu&oid=asset" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦投信</a></li>
					<li><a href="https://www.fubon.com/futures/home/index.htm?ctype=B&cid=menu&oid=futures" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦期貨</a></li>
					<li><a href="https://www.fubon.com/investment-services/home/index.htm?ctype=B&cid=menu&oid=investment" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦投顧</a></li>
					<li><a href="https://www.fubon.com/direct/home/index.htm?ctype=B&cid=menu&oid=direct" target="_blank"><i class="m-icon m-icon-chevron-right"></i>富邦行銷 | 富昇保代</a></li>
				</ul>
			</div>
		</li>
	</ul>
</div>