<div>
	<ul class="b-clearfix ng-nav-item">
		<li class="b-middle">
			<a href="/financialholdings/about/info.html">
				<em>關於富邦金控</em>
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
			<div ng-style="{'left' : Common.Nav.Submenu.Left , 'margin-left' : Common.Nav.Submenu.MarginLeft}">
				<ul class="b-clearfix">
					<li><a href="/financialholdings/about/info.html"><i class="m-icon m-icon-nav-arrow"></i><em>富邦金控簡介</em></a></li>
					<li><a href="/financialholdings/about/business_philosophy.html"><i class="m-icon m-icon-nav-arrow"></i><em>核心價值</em></a></li>
					<li><a href="/financialholdings/about/team.html"><i class="m-icon m-icon-nav-arrow"></i><em>經營團隊</em></a></li>
					<li><a href="/financialholdings/about/sub.html"><i class="m-icon m-icon-nav-arrow"></i><em>金控子公司成員</em></a></li>
					<li><a href="/financialholdings/about/honor.html"><i class="m-icon m-icon-nav-arrow"></i><em>專業殊榮</em></a></li>
					<li><a href="/financialholdings/about/milestone.html"><i class="m-icon m-icon-nav-arrow"></i><em>大事記</em></a></li>
				</ul>
			</div>
		</li>
		<li class="b-middle">
			<a href="/financialholdings/story/future.html">
				<em>品牌故事</em>
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
			<div ng-style="{'left' : Common.Nav.Submenu.Left , 'margin-left' : Common.Nav.Submenu.MarginLeft}">
				<ul class="b-clearfix">
					<li><a href="/financialholdings/story/future.html"><i class="m-icon m-icon-nav-arrow"></i><em>延續傳承 走向未來</em></a></li>
					<li><a href="/financialholdings/story/positive.html"><i class="m-icon m-icon-nav-arrow"></i><em>正向的力量</em></a></li>
					<li><a href="/financialholdings/story/identity.html"><i class="m-icon m-icon-nav-arrow"></i><em>富邦品牌標誌</em></a></li>
				</ul>
			</div>
		</li>
		<li class="b-middle">
			<a href="/financialholdings/csr/chairmans_messages.html">
				<em>企業社會責任</em>
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
			<div ng-style="{'left' : Common.Nav.Submenu.Left , 'margin-left' : Common.Nav.Submenu.MarginLeft}">
				<ul class="b-clearfix">
					<li><a href="/financialholdings/csr/chairmans_messages.html"><i class="m-icon m-icon-nav-arrow"></i><em>董事長的話</em></a></li>
					<li><a href="/financialholdings/csr/sustainable_operations.html"><i class="m-icon m-icon-nav-arrow"></i><em>永續經營</em></a></li>
					<li><a href="/financialholdings/csr/corporate_governance.html"><i class="m-icon m-icon-nav-arrow"></i><em>公司治理</em></a></li>
					<li><a href="/financialholdings/csr/commitment.html"><i class="m-icon m-icon-nav-arrow"></i><em>客戶承諾</em></a></li>
					<li><a href="/financialholdings/csr/care.html"><i class="m-icon m-icon-nav-arrow"></i><em>員工關懷</em></a></li>
					<li><a href="/financialholdings/csr/core_competencies.html"><i class="m-icon m-icon-nav-arrow"></i><em>核心職能</em></a></li>
					<li><a href="/financialholdings/csr/green.html"><i class="m-icon m-icon-nav-arrow"></i><em>綠色金融</em></a></li>
					<li><a href="/financialholdings/csr/foundation.html"><i class="m-icon m-icon-nav-arrow"></i><em>基金會</em></a></li>
					<li><a href="/financialholdings/csr/sponsorship.html"><i class="m-icon m-icon-nav-arrow"></i><em>體育贊助</em></a></li>
					<li><a href="/financialholdings/csr/stakeholders.html"><i class="m-icon m-icon-nav-arrow"></i><em>利害關係人專區</em></a></li>
					<li><a href="/financialholdings/csr/contact.html"><i class="m-icon m-icon-nav-arrow"></i><em>聯絡我們</em></a></li>
					<li><a href="/financialholdings/csr/news.html"><i class="m-icon m-icon-nav-arrow"></i><em>最新消息</em></a></li>
					<li><a href="/financialholdings/csr/media.html"><i class="m-icon m-icon-nav-arrow"></i><em>影音專區</em></a></li>
					<li><a href="/financialholdings/csr/downloadlist.html"><i class="m-icon m-icon-nav-arrow"></i><em>企業社會責任報告下載</em></a></li>
				</ul>
			</div>
		</li>
		<li class="b-middle">
			<a href="/financialholdings/ir/overview.html">
				<em>投資人關係</em>
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
			<div ng-style="{'left' : Common.Nav.Submenu.Left , 'margin-left' : Common.Nav.Submenu.MarginLeft}">
				<ul class="b-clearfix">
					<li><a href="/financialholdings/ir/overview.html"><i class="m-icon m-icon-nav-arrow"></i><em>公司概況</em></a></li>
					<li><a href="/financialholdings/ir/financial.html"><i class="m-icon m-icon-nav-arrow"></i><em>財務資訊</em></a></li>
					<li><a href="/financialholdings/ir/shareholder_services.html"><i class="m-icon m-icon-nav-arrow"></i><em>股務資訊</em></a></li>
					<li><a href="/financialholdings/ir/announcements.html"><i class="m-icon m-icon-nav-arrow"></i><em>活動與公告</em></a></li>
					<li><a href="/financialholdings/ir/contact.html"><i class="m-icon m-icon-nav-arrow"></i><em>聯絡我們</em></a></li>
				</ul>
			</div>
		</li>
		<li class="b-middle">
			<a href="/financialholdings/governance/status.html">
				<em>公司治理</em>
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
			<div ng-style="{'left' : Common.Nav.Submenu.Left , 'margin-left' : Common.Nav.Submenu.MarginLeft}">
				<ul class="b-clearfix">
					<li><a href="/financialholdings/governance/status.html"><i class="m-icon m-icon-nav-arrow"></i><em>公司治理現況</em></a></li>
					<li><a href="/financialholdings/governance/framework.html"><i class="m-icon m-icon-nav-arrow"></i><em>公司治理架構</em></a></li>
					<li><a href="/financialholdings/governance/operation.html"><i class="m-icon m-icon-nav-arrow"></i><em>公司治理運作情形</em></a></li>
					<li><a href="/financialholdings/governance/shareholders.html"><i class="m-icon m-icon-nav-arrow"></i><em>股東會</em></a></li>
					<li><a href="/financialholdings/governance/board_of_directors.html"><i class="m-icon m-icon-nav-arrow"></i><em>董事會</em></a></li>
					<li><a href="/financialholdings/governance/committee.html"><i class="m-icon m-icon-nav-arrow"></i><em>功能性委員會</em></a></li>
					<li><a href="/financialholdings/governance/organization.html"><i class="m-icon m-icon-nav-arrow"></i><em>內部稽核組織及運作</em></a></li>
					<li><a href="/financialholdings/governance/regulation.html"><i class="m-icon m-icon-nav-arrow"></i><em>公司重要章則</em></a></li>
					<li><a href="/financialholdings/governance/mail.html"><i class="m-icon m-icon-nav-arrow"></i><em>獨立董事信箱</em></a></li>
				</ul>
			</div>
		</li>
		<li class="b-middle">
			<a href="/financialholdings/news/list.html">
				<em>新聞中心</em>
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-right"></i>
					<i class="m-icon m-icon-arrow-angle-down"></i>
				</span>
			</a>
		</li>
	</ul>
	<span class="m-nav-bar" ng-class="{'is-show' : Common.Nav.Bar.Hover}" ng-style="{'left' : Common.Nav.Bar.Left , 'width' : Common.Nav.Bar.Width}"></span>
</div>