<!-- ==================== l-side begin =================== -->
<div class="l-side">
	<aside class="m-aside m-aside-accordion ng-aside-accordion" ng-class="{'is-selected' : Common.Aside.Selected}">
		<header class="m-aside-hd">
			<button class="ng-cloak ng-aside-select">
				{{ Common.Aside.Toggle.Text }}
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-down"></i>
					<i class="m-icon m-icon-arrow-angle-up"></i>
				</span>
			</button>
		</header>
		<main class="m-aside-bd">
			<ul id="aside-item" class="ng-aside-accordion-item">
				<li data-channel="jobs">
					<h6>
						<a href="/financialholdings/hr/jobs.html" class="b-middle">
							<em>焦點職缺</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>目前職缺查詢</em>
							<span class="m-icon-stack m-icon-toggle">
								<i class="m-icon m-icon-plus"></i>
								<i class="m-icon m-icon-minus"></i>
							</span>
						</a>
					</h6>
					<div>
						<ul>
							<li>
								<a href="https://www.fubon.com/hr/join/join1_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦金控(總處、各處及中心)</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join8_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦人壽</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join2_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>台北富邦銀行</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join7_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦產險</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join3_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦證券</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join4_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦投信</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join6_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦投顧</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join5_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦期貨</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/hr/join/join9_record.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦行銷</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/life_vn/en/join_us.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦人壽(越南)</em>
								</a>
							</li>
							<li>
								<a href="http://www.fubonbank.com.hk/web/html/sh_careers_e.html" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦銀行(香港)</em>
								</a>
							</li>
							<li>
								<a href="http://www.fubonchina.com/joinus.php?cid=20" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦華ㄧ銀行(大陸)</em>
								</a>
							</li>
							<li>
								<a href="http://www.fubon.com.cn/" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦財險(大陸)</em>
								</a>
							</li>
							<li>
								<a href="https://www.fubon.com/INS_VN/?ctype=B&cid=menu&oid=ins" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦產險(越南)</em>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li data-channel="development">
					<h6>
						<a href="/financialholdings/hr/development.html" class="b-middle">
							<em>多元學習與發展</em>
						</a>
					</h6>
				</li>
				<li data-channel="life">
					<h6>
						<a href="/financialholdings/hr/life.html" class="b-middle">
							<em>快樂富邦人</em>
						</a>
					</h6>
				</li>
				<li data-channel="announcements">
					<h6>
						<a href="/financialholdings/hr/announcements.html" class="b-middle">
							<em>重要資訊公告</em>
						</a>
					</h6>
				</li>
				<li data-channel="FAQ">
					<h6>
						<a href="/financialholdings/hr/FAQ.html" class="b-middle">
							<em>FAQ</em>
						</a>
					</h6>
				</li>
			</ul>
		</main>
	</aside>
	<div class="m-aside">
		<div class="m-aside-bd">
			<ul class="m-icon-stack m-icon-circle-group b-row">
				<li class="b-col-md-12 b-col-sm-6 b-col-xs-6 b-align-md-center b-align-sm-right b-align-xs-center">
					<a href="https://www.fubon.com/hr/download/Resume.doc" class="m-icon-circle-item" target="_blank">
						<span>
							<i class="m-icon m-icon-download m-icon-size-md-4 m-icon-size-sm-4 m-icon-size-xs-4 is-absolute"></i>
							<i class="m-icon m-icon-circle m-icon-size-md-8 m-icon-size-sm-8 m-icon-size-xs-8"></i>
						</span>
						<em>富邦金控履歷下載</em>
					</a>
				</li>
				<li class="b-col-md-12 b-col-sm-6 b-col-xs-6 b-align-md-center b-align-sm-left b-align-xs-center">
					<a href="/financialholdings/hr/contact.html" class="m-icon-circle-item">
						<span>
							<i class="m-icon m-icon-comment m-icon-size-md-4 m-icon-size-sm-4 m-icon-size-xs-4 is-absolute"></i>
							<i class="m-icon m-icon-circle m-icon-size-md-8 m-icon-size-sm-8 m-icon-size-xs-8"></i>
						</span>
						<em>與我們聯繫</em>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>
<!-- ==================== l-side end =================== -->