<!-- ==================== l-main-hd begin =================== -->
<header class="l-main-hd b-clearfix">
	<div class="m-media">
		<div class="m-media-group owl-carousel">
			<div class="m-media-item is-center-top">
				<small class="m-media-message"><p>TAIPEI</p></small>
				<figure class="m-media-figure">
					<img class="is-loaded owl-lazy" data-src="/financialholdings/Content/img/home/kv-taipei{{ Home.Images.Night }}.jpg" alt="TAIPEI">
				</figure>
			</div>
			<div class="m-media-item is-center-top">
				<small class="m-media-message"><p>SHANGHAI</p></small>
				<figure class="m-media-figure">
					<img class="is-loaded owl-lazy" data-src="/financialholdings/Content/img/home/kv-shanghai{{ Home.Images.Night }}.jpg" alt="SHANGHAI">
				</figure>
			</div>
			<div class="m-media-item is-center-top">
				<small class="m-media-message"><p>HONG KONG</p></small>
				<figure class="m-media-figure">
					<img class="is-loaded owl-lazy" data-src="/financialholdings/Content/img/home/kv-hongkong{{ Home.Images.Night }}.jpg" alt="HONG KONG">
				</figure>
			</div>
			<div class="m-media-item is-center-top">
				<small class="m-media-message"><p>LOS ANGELES</p></small>
				<figure class="m-media-figure">
					<img class="is-loaded owl-lazy" data-src="/financialholdings/Content/img/home/kv-losangeles{{ Home.Images.Night }}.jpg" alt="LOS ANGELES">
				</figure>
			</div>
		</div>
		<!--#include virtual="/financialholdings/common_share.inc" -->
		<div class="m-media-info">
			<header class="m-media-info-hd">
				<h3>正向的力量</h3>
			</header>
			<main class="m-media-info-bd">
				<p>讓世界持續美好</p>
				<div class="m-button-group">
					<a href="/financialholdings/story/positive.html" class="m-button b-primary">了解更多</a>
				</div>
			</main>
		</div>
	</div>
</header>
<!-- ==================== l-main-hd end =================== -->