<!-- ==================== l-side begin =================== -->
<div class="l-side">
	<aside class="m-aside m-aside-list">
		<header class="m-aside-hd b-clearfix">
			<h5>熱門連結</h5>
		</header>
		<main class="m-aside-bd">
			<ul id="aside-item">
				<li>
					<h6>
						<a href="/financialholdings/announce/list.html" class="b-middle">
							<em>重要公告</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="/financialholdings/sub/facebook.html" class="b-middle">
							<em>富邦子公司/基金會粉絲團</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="https://www.youtube.com/watch?v=UTDNB3cLc40" class="b-middle" target="_blank">
							<em>富邦金控｢正向的力量 讓世界持續美好｣影片拍攝幕後花絮</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="https://www.facebook.com/FUBON" class="b-middle" target="_blank">
							<em>富邦金控FB粉絲募集中</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="http://www.fubonbraves.com/" class="b-middle" target="_blank">
							<em>富邦勇士籃球隊，勇不止息</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="http://www.fuboncharity.org.tw/chinese/news_content.php?id=364" class="b-middle" target="_blank">
							<em>周杰倫代言「用愛心做朋友」助學活動</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="http://www.fubonart.org.tw/ugC_LectureKind.asp?hidLectureKindID=1" class="b-middle" target="_blank">
							<em>富邦藝術基金會富邦講堂</em>
						</a>
					</h6>
				</li>
			</ul>
		</main>
	</aside>
</div>
<!-- ==================== l-side end =================== -->