<!-- ==================== l-side begin =================== -->
<div class="l-side">
	<aside class="m-aside m-aside-accordion ng-aside-accordion" ng-class="{'is-selected' : Common.Aside.Selected}">
		<header class="m-aside-hd">
			<button class="ng-cloak ng-aside-select">
				{{ Common.Aside.Toggle.Text || '搜尋結果' }}
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-down"></i>
					<i class="m-icon m-icon-arrow-angle-up"></i>
				</span>
			</button>
		</header>
		<main class="m-aside-bd">
			<ul id="aside-item" class="ng-aside-accordion-item">
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>顯示所有結果</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>發布日期</em>
							<span class="m-icon-stack m-icon-toggle">
								<i class="m-icon m-icon-plus"></i>
								<i class="m-icon m-icon-minus"></i>
							</span>
						</a>
					</h6>
					<div>
						<ul>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>近一個月 (109)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>近三個月 (204)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>近半年 (319)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>近一年 (432)</em>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>類型</em>
							<span class="m-icon-stack m-icon-toggle">
								<i class="m-icon m-icon-plus"></i>
								<i class="m-icon m-icon-minus"></i>
							</span>
						</a>
					</h6>
					<div>
						<ul>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>網頁 (362)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>表單 (326)</em>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>資料來源</em>
							<span class="m-icon-stack m-icon-toggle">
								<i class="m-icon m-icon-plus"></i>
								<i class="m-icon m-icon-minus"></i>
							</span>
						</a>
					</h6>
					<div>
						<ul>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦證券 (31)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦期貨 (10)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦產險 (102)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦金控 (4)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦投信 (30)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>富邦行銷 (9)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>台北富邦銀行–財富金融 (47)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>台北富邦銀行–個人貸款 (15)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>台北富邦銀行–信用卡 (330)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>台北富邦銀行–企業金融 (6)</em>
								</a>
							</li>
							<li>
								<a href="javascript:;" class="ng-member">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>台北富邦銀行 (406)</em>
								</a>
							</li>
						</ul>
					</div>
				</li>
			</ul>
		</main>
	</aside>
</div>
<!-- ==================== l-side end =================== -->