<!-- ==================== l-side begin =================== -->
				<div class="l-side">
					<aside class="m-aside m-aside-accordion ng-aside-accordion" ng-class="{'is-selected' : Common.Aside.Selected}">
						<header class="m-aside-hd">
							<button class="ng-cloak ng-aside-select">
								{{ Common.Aside.Toggle.Text }}
								<span class="m-icon-stack m-icon-toggle">
									<i class="m-icon m-icon-arrow-angle-down"></i>
									<i class="m-icon m-icon-arrow-angle-up"></i>
								</span>
							</button>
						</header>
						<main class="m-aside-bd">
							<ul id="aside-item" class="ng-aside-accordion-item">
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>董事長的話</em>
										</a>
									</h6>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>永續經營</em>
											<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">關於富邦金控</a></li>
											<li><a href="javascript:;">核心價值</a></li>
											<li><a href="javascript:;">重要經營成果</a></li>
											<li><a href="javascript:;">企業社會責任守則</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>公司治理</em>
										<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">法令遵循</a></li>
											<li><a href="javascript:;">風險管理</a></li>
											<li><a href="javascript:;">稽核制度執行</a></li>
											<li><a href="javascript:;">資訊揭露透明度</a></li>
											<li><a href="javascript:;">投資人關係</a></li>
											<li><a href="javascript:;">公司治理情形</a></li>
											<li><a href="javascript:;">道德與誠信</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>客戶承諾</em>
										<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">客戶服務</a></li>
											<li><a href="javascript:;">客戶溝通</a></li>
											<li><a href="javascript:;">隱私權議題</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>員工關懷</em>
											<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">富邦職場 人人平等</a></li>
											<li><a href="javascript:;">富邦培育 多元有趣</a></li>
											<li><a href="javascript:;">富邦福利 豐富美麗</a></li>
											<li><a href="javascript:;">富邦環境 人人肯定</a></li>
											<li><a href="javascript:;">富邦員工 有效溝通</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>核心職能</em>
										<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">協助解決社會問題</a></li>
											<li><a href="javascript:;">因應氣候變遷</a></li>
											<li><a href="javascript:;">因應社會變遷</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>綠色金融</em>
										<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">邁向低碳企業</a></li>
											<li><a href="javascript:;">行動化服務</a></li>
											<li><a href="javascript:;">價值鏈管理</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>基金會</em>
										<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">富邦慈善基金會</a></li>
											<li><a href="javascript:;">富邦文教基金會</a></li>
											<li><a href="javascript:;">富邦藝術基金會</a></li>
											<li><a href="javascript:;">台北富邦銀行慈善基金會</a></li>
										</ul>
									</div>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>體育贊助</em>
										</a>
									</h6>
								</li>
								<li data-channel="stackholders">
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>利害關係人專區</em>
										<span class="m-icon-stack m-icon-toggle">
												<i class="m-icon m-icon-plus"></i>
												<i class="m-icon m-icon-minus"></i>
											</span>
										</a>
									</h6>
									<div>
										<ul>
											<li><a href="javascript:;">議和與重大議題</a></li>
											<li><a href="/financialholdings/citizenship/stackholders/feedback.html">意見回饋</a></li>
										</ul>
									</div>
								</li>
								<li data-channel="news">
									<h6>
										<a href="/financialholdings/citizenship/news/news.html" class="b-middle">
											<em>最新消息</em>
										</a>
									</h6>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>影音專區</em>
										</a>
									</h6>
								</li>
								<li>
									<h6>
										<a href="javascript:;" class="b-middle">
											<em>企業社會責任報告下載</em>
										</a>
									</h6>
								</li>
							</ul>
						</main>
					</aside>
					<aside class="m-aside">
						<main class="m-aside-bd">
							<div class="contactbtn">
							<a href="" class="call">聯絡我們</a>
							<a href="" class="fbfans">金控粉絲團</a>
							</div>
						</main>
					</aside>
				</div>
				<!-- ==================== l-side end =================== -->