<!-- ==================== l-main-hd begin =================== -->
<header class="l-main-hd b-clearfix">
	<div class="m-media ng-image-load">
		<div class="b-loading">
			<span class="m-icon-stack">
				<i class="m-icon m-icon-fubon-blue is-absolute"></i>
				<i class="m-icon m-icon-fubon-green"></i>
			</span>
		</div>
		<div class="m-media-group">
			<div class="m-media-item">
				<figure class="m-media-figure">
					<img ng-src="/financialholdings/Content/img/about/kv.jpg" alt="富邦金控-關於富邦金控">
				</figure>
			</div>
		</div>
		<!--#include virtual="/financialholdings/common_share.inc" -->
	</div>
</header>
<!-- ==================== l-main-hd end =================== -->