<!-- ==================== l-side begin =================== -->
<div class="l-side">
	<aside class="m-aside m-aside-accordion ng-aside-accordion" ng-class="{'is-selected' : Common.Aside.Selected}">
		<header class="m-aside-hd b-clearfix">
			<button class="ng-cloak ng-aside-select">
				{{ Common.Aside.Toggle.Text }}
				<span class="m-icon-stack m-icon-toggle">
					<i class="m-icon m-icon-arrow-angle-down"></i>
					<i class="m-icon m-icon-arrow-angle-up"></i>
				</span>
			</button>
		</header>
		<main class="m-aside-bd">
			<ul id="aside-item" class="ng-aside-accordion-item">
				<li data-channel="status">
					<h6>
						<a href="/financialholdings/governance/status.html" class="b-middle">
							<em>公司治理現況</em>
						</a>
					</h6>
				</li>
				<li data-channel="framework">
					<h6>
						<a href="/financialholdings/governance/framework.html" class="b-middle">
							<em>公司治理架構</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="http://www.corpasia.net/taiwan/2881/engovernancepage/13/CH/CG.pdf" target="_blank" class="b-middle">
							<em>公司治理運作情形</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>股東會</em>
							<span class="m-icon-stack m-icon-toggle">
								<i class="m-icon m-icon-plus"></i>
								<i class="m-icon m-icon-minus"></i>
							</span>
						</a>
					</h6>
					<div>
						<ul>
							<li data-channel="letter">
								<a href="/financialholdings/governance/letter.html">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>致股東報告書</em>
								</a>
							</li>
							<li data-channel="shareholders">
								<a href="/financialholdings/governance/shareholders.html">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>股東會資訊</em>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li>
					<h6>
						<a href="javascript:;" class="b-middle">
							<em>董事會</em>
							<span class="m-icon-stack m-icon-toggle">
								<i class="m-icon m-icon-plus"></i>
								<i class="m-icon m-icon-minus"></i>
							</span>
						</a>
					</h6>
					<div>
						<ul>
							<li data-channel="board_of_directors">
								<a href="/financialholdings/governance/board_of_directors.html">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>董事會成員</em>
								</a>
							</li>
							<li data-channel="election">
								<a href="/financialholdings/governance/election.html">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>獨立董事選任資訊</em>
								</a>
							</li>
							<li>
								<a href="http://mops.twse.com.tw/mops/web/t93sc03_1" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>董事會出席情形</em>
								</a>
							</li>
							<li data-channel="resolutions">
								<a href="/financialholdings/governance/resolutions.html">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>董事會重要決議</em>
								</a>
							</li>
							<li>
								<a href="http://www.mzcan.com/taiwan/2881/engovernancepage/20/CH/Rules%20Governing%20Procedures%20for%20Meeting%20of%20Board%20of%20Directors.pdf" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>董事會議事規範</em>
								</a>
							</li>
							<li>
								<a href="http://mops.twse.com.tw/mops/web/t93sc03_1" target="_blank">
									<i class="m-icon m-icon-arrow-angle-right"></i>
									<em>董事進修</em>
								</a>
							</li>
						</ul>
					</div>
				</li>
				<li data-channel="committee">
					<h6>
						<a href="/financialholdings/governance/committee.html" class="b-middle">
							<em>功能性委員會</em>
						</a>
					</h6>
				</li>
				<li data-channel="organization">
					<h6>
						<a href="/financialholdings/governance/organization.html" class="b-middle">
							<em>內部稽核組織及運作</em>
						</a>
					</h6>
				</li>
				<li data-channel="regulation">
					<h6>
						<a href="/financialholdings/governance/regulation.html" class="b-middle">
							<em>公司重要章則</em>
						</a>
					</h6>
				</li>
				<li>
					<h6>
						<a href="mailto:ibtnag@ntu.edu.tw" class="b-middle">
							<em>獨立董事信箱</em>
						</a>
					</h6>
				</li>
			</ul>
		</main>
	</aside>
</div>
<!-- ==================== l-side end =================== -->